name: "Build & Release"

on:
  push:
    branches:
      - main


jobs:  # Telling what jobs we need to happen
  build:      # Specify the building name and machine
    name: Build & Release  # you can name the build whatever you want
    runs-on: macos-latest # here we selected macos-latest to be able to get ios build

    steps:
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      #2 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      #3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      #5 Build APK
      - name: Build APK
        run: flutter build apk --release

      #6 Upload APK
      - name: Upload APK 
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: |
            build/app/outputs/flutter-apk/app-release.apk

      #7 Send Email
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.solvenya.sd
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Build Completed
          body: The build has been completed successfully. You can download the APK from the link below
              ${{ github.server_url }}/${{ github.repository }}/suites/${{ github.run_id }}/artifacts/${{ steps.upload-apk.outputs.artifact_id }}
          to: ahmed.alsabonabi@gmail.com
          from: ahmed@solvenya.sd
          attachments: build/app/outputs/flutter-apk/app-release.apk
